In [1]:
import numpy as np

In [2]:
matriz_1 = np.array([[7.0, 8.0], [5.0, 1.0]])
matriz_2 = np.array([[3.0, 4.0], [4.0, 2.0]])
 # soma de matrizes
print(matriz_1 + matriz_2)

[[10. 12.]
 [ 9.  3.]]


In [3]:
# multiplicação de matrizes
print(matriz_1 * matriz_2)

[[21. 32.]
 [20.  2.]]


In [4]:
# subtração de matrizes
print(matriz_1 - matriz_2)

[[ 4.  4.]
 [ 1. -1.]]


In [5]:
# divisão de matrizes
print(matriz_1 / matriz_2)

[[2.33333333 2.        ]
 [1.25       0.5       ]]


A biblioteca collections do Python possui um recurso interessante para lidar com listas: os chamados deques.

Deque Python
Em Python, deque é uma estrutura de dados que permite a ordenação de itens de maneira similar a uma fila.

Para criar um deque:

In [6]:
import collections

In [7]:
dias_da_semana = collections.deque([
"Dom",
"Seg",
"Ter",
"Qua",
"Qui",
"Sex",
"Sab"
])

print(dias_da_semana)

deque(['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'])


In [8]:
#É possível adicionar itens usando a função append():

# Adicionando itens
dias_da_semana.append("Janeiro")
print(dias_da_semana)

deque(['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab', 'Janeiro'])


In [9]:
#Para remover itens da fila, pode-se utilizar a função popleft( ):

# Removendo itens da fila
dias_da_semana.popleft()
print(dias_da_semana)

deque(['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab', 'Janeiro'])


Perceba que em uma fila, espera-se que o primeiro item inserido seja o primeiro item removido. No exemplo, como “Dom” foi o primeiro valor inserido, logo ele será o primeiro a ser removido.

Entretanto, pode-se utilizar as características de um objeto deque para remover itens de qualquer parte da lista. Podemos por exemplo, utilizar deque para tratar a lista como se fosse uma pilha. Nesse caso, poderíamos usar a função pop( ) para remover o último item acrescentado. Podemos ainda corrigir nosso deque utilizando a função appendleft() para acrescentar novamente o dia incorretamente removido (domingo). Veja:

In [10]:
# Removendo itens da lista [ pilha ]
dias_da_semana.pop()
 
# adicione novamente no começo da fila
dias_da_semana.appendleft("Dom")
print(dias_da_semana)

deque(['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'])


Grande parte dos softwares utilizados no cotidiano e no mercado possuem os tipos abstratos de dados chamados filas e pilhas.

Pilhas e filas consistem em estruturas de dados úteis para o programador pois podem ser utilizados em diversas aplicações que simplificam a estrutura do software.

 A seguir, será apresentado um resumo de como se implementar essas estruturas em Python.

##Pilhas

Começamos por Pilhas, essas estruturas possuem operações de inserção e remoção e seguem uma forma específica em que o último item inserido será o primeiro a ser removido, ou seja, segue o princípio de (Last-In, First-Out — LIFO) , o último a entrar na pilha, é o primeiro a sair.

Em Python, primeiramente devemos inserir os elementos na pilha e depois remover:

O método append() insere um elemento ao final de uma lista. Você pode interpretar isso como se fosse o topo de uma pilha, imagine uma pilha de caixas ao inserir uma nova caixa ela estará no topo da pilha, ao remover você iniciará por ela.

In [14]:
pilha = [1,2,3,4]
print ("Pilha de caixas", pilha)

# operação de push com o método append()
pilha.append(5)
print("Inserindo caixa 5", pilha)  # [1, 2, 3, 4, 5]

pilha.append(6)
print("Inserindo caixa 6", pilha)  # [1, 2, 3, 4, 5, 6]

Pilha de caixas [1, 2, 3, 4]
Inserindo caixa 5 [1, 2, 3, 4, 5]
Inserindo caixa 6 [1, 2, 3, 4, 5, 6]


Se usarmos o método pop() nessa mesma lista, o valor removido, quando nenhum argumento é passado na chamada, será o último valor inserido. Logo, podemos concluir que o método pop() remove itens do topo da pilha.

In [15]:
# operação de pop com o método pop()
pilha.pop()
print("Mostrar pilha com elemento removido", pilha)

pilha.pop()
print("Mostrar pilha com elemento removido", pilha)

Mostrar pilha com elemento removido [1, 2, 3, 4, 5]
Mostrar pilha com elemento removido [1, 2, 3, 4]


A estrutura de dados do tipo pilhas facilita o programador a priorizar determinadas tarefas em que por exemplo a inserção mais recente é a primeira a ser removida ou colocada em execução.

#Filas

A estrutura de dados do tipo Filas está presente também em várias tarefas que executamos no nosso dia-a-dia. Imagine uma fila de banco, supermercado, uma simples fila de atendimento em qualquer estabelecimento. Sim! As filas estão presentes em muitas aplicações e elas tem uma característica diferente das Pilhas.

Imagina que você chega em uma estabelecimento e temos uma fila de espera, certamente você será o último da fila e consequentemente o último a ser atendido correto?

Imagine uma fila de impressão de documentos em uma impressora, que você enviou para um servidor de impressão. Elas apresentam o mesmo princípio, o software de gerenciamento de impressão, o último arquivo que você solicitou a impressão também será o último a ser impresso e o primeiro claramente será o primeiro a sair na impressora.

As filas podem ser implementadas como listas, uma vez que elas apresentam uma ordem de entrada e saída de itens. Os métodos para inserção e remoção de itens são os seguintes:

.append (elemento): insere o item ao final da lista.

.insert (índice, elemento): insere o item após a posição índice.

.pop (índice): remove e retorna o item contido na posição índice.

Veja um exemplo implementando em Python a seguir.

Imagine que queremos imprimir algumas páginas específicas em uma impressora, na sequência seria a página 5, 10, 15 e 20. Caso desejamos imprimir a primeira página, qual deverá sair primeiro e ser removida da fila de impressão? A página 5 e como podemos fazer isso como uma fila?

Utilizando o método .pop (índice), nesse caso, inserimos o índice da posição da página a ser removida da fila de impressão.

In [16]:
fila = [5, 10, 15, 20]
print ("Páginas para impressão", fila)

# operação pop com o método pop(indice)
fila.pop(0)
print(fila)

Páginas para impressão [5, 10, 15, 20]
[10, 15, 20]


A página 5 foi removida da fila, restando apenas as páginas 10, 15 e 20.

Se novamente, fizermos fila.pop(0), será removida a página 10 e assim sucessivamente.

fila.pop(0)

print(fila)

Se você deseja inserir um elemento no final da lista, você pode utilizar o método .append.


In [17]:
# operação push com o método .append(elemento), inserimos o elemento 10 novamente no final da lista.

fila.append(10)

print(fila)

[10, 15, 20, 10]
